language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-helloexpress' ]; then cd .. && eval "mv $currentfolder generator-helloexpress" && cd generator-helloexpress; fi

